// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"cloud.google.com/go/bigquery"
	"context"
	"github.com/MadHive/google-cloud-go-testing/bigquery/bqiface"
	"sync"
)

// Ensure, that ExtractorMock does implement bqiface.Extractor.
// If this is not the case, regenerate this file with moq.
var _ bqiface.Extractor = &ExtractorMock{}

// ExtractorMock is a mock implementation of bqiface.Extractor.
//
//     func TestSomethingThatUsesExtractor(t *testing.T) {
//
//         // make and configure a mocked bqiface.Extractor
//         mockedExtractor := &ExtractorMock{
//             JobIDConfigFunc: func() *bigquery.JobIDConfig {
// 	               panic("mock out the JobIDConfig method")
//             },
//             RunFunc: func(in1 context.Context) (bqiface.Job, error) {
// 	               panic("mock out the Run method")
//             },
//             SetExtractConfigFunc: func(in1 bqiface.ExtractConfig)  {
// 	               panic("mock out the SetExtractConfig method")
//             },
//         }
//
//         // use mockedExtractor in code that requires bqiface.Extractor
//         // and then make assertions.
//
//     }
type ExtractorMock struct {
	// JobIDConfigFunc mocks the JobIDConfig method.
	JobIDConfigFunc func() *bigquery.JobIDConfig

	// RunFunc mocks the Run method.
	RunFunc func(in1 context.Context) (bqiface.Job, error)

	// SetExtractConfigFunc mocks the SetExtractConfig method.
	SetExtractConfigFunc func(in1 bqiface.ExtractConfig)

	// calls tracks calls to the methods.
	calls struct {
		// JobIDConfig holds details about calls to the JobIDConfig method.
		JobIDConfig []struct {
		}
		// Run holds details about calls to the Run method.
		Run []struct {
			// In1 is the in1 argument value.
			In1 context.Context
		}
		// SetExtractConfig holds details about calls to the SetExtractConfig method.
		SetExtractConfig []struct {
			// In1 is the in1 argument value.
			In1 bqiface.ExtractConfig
		}
	}
	lockJobIDConfig      sync.RWMutex
	lockRun              sync.RWMutex
	lockSetExtractConfig sync.RWMutex
}

// JobIDConfig calls JobIDConfigFunc.
func (mock *ExtractorMock) JobIDConfig() *bigquery.JobIDConfig {
	if mock.JobIDConfigFunc == nil {
		panic("ExtractorMock.JobIDConfigFunc: method is nil but Extractor.JobIDConfig was just called")
	}
	callInfo := struct {
	}{}
	mock.lockJobIDConfig.Lock()
	mock.calls.JobIDConfig = append(mock.calls.JobIDConfig, callInfo)
	mock.lockJobIDConfig.Unlock()
	return mock.JobIDConfigFunc()
}

// JobIDConfigCalls gets all the calls that were made to JobIDConfig.
// Check the length with:
//     len(mockedExtractor.JobIDConfigCalls())
func (mock *ExtractorMock) JobIDConfigCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockJobIDConfig.RLock()
	calls = mock.calls.JobIDConfig
	mock.lockJobIDConfig.RUnlock()
	return calls
}

// Run calls RunFunc.
func (mock *ExtractorMock) Run(in1 context.Context) (bqiface.Job, error) {
	if mock.RunFunc == nil {
		panic("ExtractorMock.RunFunc: method is nil but Extractor.Run was just called")
	}
	callInfo := struct {
		In1 context.Context
	}{
		In1: in1,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(in1)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//     len(mockedExtractor.RunCalls())
func (mock *ExtractorMock) RunCalls() []struct {
	In1 context.Context
} {
	var calls []struct {
		In1 context.Context
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}

// SetExtractConfig calls SetExtractConfigFunc.
func (mock *ExtractorMock) SetExtractConfig(in1 bqiface.ExtractConfig) {
	if mock.SetExtractConfigFunc == nil {
		panic("ExtractorMock.SetExtractConfigFunc: method is nil but Extractor.SetExtractConfig was just called")
	}
	callInfo := struct {
		In1 bqiface.ExtractConfig
	}{
		In1: in1,
	}
	mock.lockSetExtractConfig.Lock()
	mock.calls.SetExtractConfig = append(mock.calls.SetExtractConfig, callInfo)
	mock.lockSetExtractConfig.Unlock()
	mock.SetExtractConfigFunc(in1)
}

// SetExtractConfigCalls gets all the calls that were made to SetExtractConfig.
// Check the length with:
//     len(mockedExtractor.SetExtractConfigCalls())
func (mock *ExtractorMock) SetExtractConfigCalls() []struct {
	In1 bqiface.ExtractConfig
} {
	var calls []struct {
		In1 bqiface.ExtractConfig
	}
	mock.lockSetExtractConfig.RLock()
	calls = mock.calls.SetExtractConfig
	mock.lockSetExtractConfig.RUnlock()
	return calls
}
